### ISSUE TITLE
Apple TV goes to sleep when KEXP is playing (tvOS 13 issue?)

### ISSUE THREAD

**Issue by pkamb** [dbergman/KexpTVStream#11]
I started playing KEXP at 1:11 PM. Screensaver went on. At 1:26 PM, the Apple TV went to sleep while music was playing. TV remains on.

I have the default setting:

    Settings > General > Sleep After > 15 Minutes

I don't remember this being a problem prior to the recent release of tvOS 13.

**Comment by pkamb** [comment]
> ### [Release 1.6.0](https://github.com/dbergman/KexpTVStream/releases/tag/1.6.0)
 > Fixed tv sleep issue
 > KEXPPower 0.2

Is "Fixed tv sleep issue" in reference to this issue? Is that included in the release? I don't see a commit for it; interested in what the issue was.

**Comment by pkamb** [comment]
> My Apple TV just did the update, now I have a problem with pandora. I Apple TV turns off while Pandora is playing. It is like it is not recognizing the program is running and goes to sleep. I can fix it by changing the sleep mode to never, but that kinda defeats the purpose of having a sleep mode.

 > https://discussions.apple.com/thread/250701107

**Comment by dbergman** [comment]
This is fixed with version 1.7.0
