### ISSUE TITLE
Screensaver not turning on when KEXP is streaming

### ISSUE THREAD

**Issue by pkamb** [dbergman/KexpTVStream#13]
This app originally prevented the aerial flyover screensavers from starting when the app was open and in the foreground.

I opened this PR to enable screensavers during radio playback, back in 2017:

[Allow Apple TV screensaver when playing KEXP](https://github.com/dbergman/KexpTVStream/pull/5)

That change fixed the issue and screensavers were working fine for years.

But over the last 2 days I have noticed that the screensaver is no longer turning on when the app is open on screen.

The version I'm using is 1.6.1 - released Nov 5, 2019.

Was the PR change above reverted? Is there some new tvOS change that requires a different fix?

**Comment by dbergman** [comment]
Fixed with settings view.
