### ISSUE TITLE
Music now stops after 5-20 minutes.

### ISSUE THREAD

**Issue by pkamb** [dbergman/KexpTVStream#6]
After starting the stream, the app now frequently stops playing after a short amount of time. I did not notice this in the past. Over the summer, I left KEXP playing via the app for hours at a time.

I've noticed this issue recently, in the last month or so.

In that time I've upgraded to tvOS 11, from 10. I've also upgraded to the newest version of this KEXP app.

Please let me know if there are any logs or anything that would help, if you're unable to reproduce this.

**Comment by pkamb** [comment]
Possibly related in Plex:  
https://forums.plex.tv/discussion/288620/apple-tv-audio-stops-randomly

**Comment by dbergman** [comment]
I think we are good here.
